### ISSUE TITLE
请问，只能替换静态方法调用么？

### ISSUE THREAD

**Issue by shen330** [didi/DroidAssist#15]
希望替换掉实例方法，这样可行么？ 
按照文档配置 replace 节点后编译报错，看起来是只能替换静态方法的调用

Caused by: javassist.CannotCompileException: [source error] setTextColor is not static
	at javassist.expr.MethodCall.replace(MethodCall.java:257)
	at com.didichuxing.tools.droidassist.transform.SourceTargetTransformer.replaceInstrument(SourceTargetTransformer.java:270)
	... 102 more
Caused by: compile error: setTextColor is not static
	at javassist.compiler.MemberCodeGen.atMethodCallCore2(MemberCodeGen.java:689)
	at javassist.compiler.MemberCodeGen.atMethodCallCore(MemberCodeGen.java:618)
	at javassist.compiler.MemberCodeGen.atCallExpr(MemberCodeGen.java:568)
	at javassist.compiler.JvstCodeGen.atCallExpr(JvstCodeGen.java:261)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at javassist.compiler.CodeGen.atAssignCore(CodeGen.java:908)
	at javassist.compiler.CodeGen.atVariableAssign(CodeGen.java:841)
	at javassist.compiler.CodeGen.atAssignExpr(CodeGen.java:795)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:362)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at javassist.compiler.Javac.compileStmnt(Javac.java:578)
	at javassist.expr.MethodCall.replace(MethodCall.java:251)
	... 103 more

**Comment by wangwang1069** [comment]
发一下你的配置
