### ISSUE TITLE
打包签名过的apk，编译错误

### ISSUE THREAD

**Issue by cyigo** [didi/DroidAssist#2]
Caused by: java.io.IOException: Could not create empty folder D:\AndroidStudioProjects\LifeCycleLiveData\app\build\tmp\transformClassesWithDroidAssistForRelease\jar\com.android.support:design:28.0.0
	at com.android.utils.FileUtils.cleanOutputDir(FileUtils.java:95)
	at com.android.utils.FileUtils$cleanOutputDir.callStatic(Unknown Source)
	at com.didichuxing.tools.droidassist.tasks.InputTask.ensureTemporaryDir(InputTask.groovy:66)
	at com.didichuxing.tools.droidassist.tasks.InputTask.<init>(InputTask.groovy:44)
	at com.didichuxing.tools.droidassist.tasks.JarInputTask.<init>(JarInputTask.groovy:18)

帮忙看看是什么原因

**Comment by wangwang1069** [comment]
fixed at version 1.0.5

**Comment by cyigo** [comment]
谢谢，真勤奋
